version: '3.3'

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: everhome
      MYSQL_USER: everhome_spring
      MYSQL_PASSWORD: everhome_spring
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33306:3306"
    expose:
      - "3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: "/usr/bin/mysql --user=everhome_spring --password=everhome_spring --execute \"SHOW SCHEMAS;\""
      interval: 2s
      timeout: 20s
      retries: 10


  everhome:
    container_name: everhome
    image: everhome
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/everhome?serverTimezone=Europe/Kiev:
    restart: always
    command: mvn clean spring-boot:run
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
